global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "manufacturing-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]
        labels:
          service: "fastapi-backend"
          tier: "api"

  - job_name: "bentoml-model-serving"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["serving:3000"]
        labels:
          service: "bentoml-resnet50"
          tier: "ml-inference"
