import os
import sys
import time
from pathlib import Path
from typing import Any, Optional
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import bentoml
from prometheus_client import Counter, Histogram

from training.src.inference.predictor import DefectPredictor
from training.src.utils.logging import get_logger

logger = get_logger("serving.bentoml")

SERVING_INSPECTION_TOTAL = Counter(
    "bentoml_inspection_total",
    "Total inspection requests received by BentoML service",
    ["prediction"],
)
SERVING_DEFECT_TOTAL = Counter(
    "bentoml_defect_predictions_total",
    "Total defect predictions generated by BentoML service",
)
SERVING_PREDICTION_LATENCY = Histogram(
    "bentoml_prediction_latency_seconds",
    "Latency of prediction in seconds",
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
)


@bentoml.service(
    name="manufacturing_defect_service",
    traffic={"timeout": 30},
)
class DefectInspectionService:

    def __init__(self) -> None:
        checkpoint_path = os.getenv("MODEL_CHECKPOINT_PATH", "training/artifacts/checkpoints/best_model.pt")
        cp = checkpoint_path if Path(checkpoint_path).is_file() else None

        if cp:
            logger.info(f"Loading DefectPredictor with checkpoint: {cp}")
        else:
            logger.warning(
                f"Checkpoint {checkpoint_path} not found on disk. "
                "Serving with baseline ResNet-50 architecture for staging/testing."
            )

        self.predictor = DefectPredictor(
            checkpoint_path=cp,
            device=os.getenv("DEVICE", "auto"),
            model_version=os.getenv("MODEL_VERSION", "v1.0.0"),
            defect_threshold=float(os.getenv("DEFECT_THRESHOLD", "0.50")),
        )
        self.model_version = self.predictor.model_version

    @bentoml.api(route="/predict")
    def predict(
        self,
        image: Image.Image,
        product_category: Optional[str] = None,
        source_dataset: Optional[str] = None,
    ) -> dict[str, Any]:
        start = time.perf_counter()
        result = self.predictor.predict(
            image_input=image,
            product_category=product_category,
            source_dataset=source_dataset,
        )
        elapsed = time.perf_counter() - start

        pred = result["prediction"]
        SERVING_INSPECTION_TOTAL.labels(prediction=pred).inc()
        if pred == "DEFECT":
            SERVING_DEFECT_TOTAL.inc()
        SERVING_PREDICTION_LATENCY.observe(elapsed)

        return result

    @bentoml.api(route="/health")
    def health(self) -> dict[str, Any]:
        return {
            "status": "healthy",
            "service": "manufacturing_defect_service",
            "model_version": self.model_version,
            "device": str(self.predictor.device),
        }


svc = DefectInspectionService
